url_fake_generator: 'https://www.fakenamegenerator.com/'
url_gmail_register: 'https://www.google.com/intl/pt/gmail/about/#'

xpaths:
  button_create_account: '/html/body/div[2]/div[1]/div[4]/ul[1]/li[3]/a'
  input_name: '//*[@id="firstName"]'
  input_lastName: '//*[@id="lastName"]'
  input_email: '//*[@id="username"]'
  input_pass: '//*[@id="passwd"]/div[1]/div/div[1]/input'
  input_confirm: '//*[@id="confirm-passwd"]/div[1]/div/div[1]/input'
  input_next: '//*[@id="accountDetailsNext"]'
  input_number: '//*[@id="phoneNumberId"]'
  input_phoneNext: '//*[@id="gradsIdvPhoneNext"]'
  field_msg_error: '//*[@id="view_container"]/form/div[2]/div/div[1]/div/div[2]/div[2]'